# Generated by Django 5.2.1 on 2025-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_alter_cinemas_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemas',
            name='cinema_youtube_link',
            field=models.URLField(default=''),
        ),
    ]
