# Generated by Django 5.2.1 on 2025-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_cinemas_cinema_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='cinema_youtube_link',
            field=models.URLField(default='https://www.youtube.com/watch?v='),
        ),
    ]
